### PR TITLE
beutify readme, fuggly uptown style

### PR DESCRIPTION
**Pull request by un1versal**
@Mottie 

I played a little with negative spaces there, maybe Ill do that for a revamped Stylish logo too

preview https://github.com/un1versal/GitHub-Dark-Script/blob/Born-to-Be-Blue/README.md

### CODE REVIEW

**Comment by Mottie** [comment]
Nice! Umm, but should the brackets not look all stretched out on the bottom half?

**Comment by silverwind** [comment]
BTW, can you export your images to SVG and link to those instead? Makes it much easier to edit and works better on Retina or Retina-like displays :)

You could submit them to https://github.com/StylishThemes/logo and then link to the raw files from that repo ideally :)

**Comment by un1versal** [comment]
> BTW, can you export your images to SVG and link to those instead? Makes it much easier to edit and works better on Retina or Retina-like displays :)

I might, not atm though, they need more work, its a pita GitHub dont let you do relative links with svg's

> Nice! Umm, but should the brackets not look all stretched out on the bottom half?

depends on how retarded you want it to look

**Comment by Mottie** [comment]
retarded is my favorite flavor of gummy bears.

**Comment by un1versal** [comment]
Oh btw dont merge it, just wanted to show it. atm,

**Comment by un1versal** [comment]
unless theres any comments this is OK to go

**Comment by Mottie** [comment]
Thanks!

**Pull request merged**
